# Generated by Django 3.0.4 on 2020-03-31 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ID', models.IntegerField(auto_created=True)),
                ('itemName', models.CharField(default='none', max_length=100)),
                ('itemDescription', models.CharField(default='', max_length=200)),
                ('itemEssentialFlag', models.BooleanField(default='True')),
                ('itemQty', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
